name: Build and Deploy to Droplet

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
          
            # Install rsync if it's not already installed
            sudo apt-get update && sudo apt-get install -y rsync
      
            # Copy the contents of the dist folder to the droplet using rsync
            rsync -avz --delete ./dist/ root@${{ secrets.DROPLET_HOST }}:/var/www/portfolio-v1
      
            # Reload Nginx to apply changes
            sudo systemctl reload nginx

          
          
